/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_loli_sc_core_HotKeyRegister */

#ifndef _Included_io_loli_sc_core_HotKeyRegister
#define _Included_io_loli_sc_core_HotKeyRegister
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_loli_sc_core_HotKeyRegister
 * Method:    bindAndListen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_loli_sc_core_HotKeyRegister_bindAndListen
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
